on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Handle release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create new release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - name: Update README.md
        if: ${{ steps.release.outputs.release_created }}
        run: |
          sed -i 's/Current version: .*/Current version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}/' README.md
      - name: Commit updated README.md
        if: ${{ steps.release.outputs.release_created }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update version in README to ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"