name: Validate

on:
  push:

jobs:
  validate-hacs-plugin:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "plugin"